### ISSUE TITLE
Ability to send sms over http

### ISSUE THREAD

**Issue by Flinner** [headersalreadysent/tinycodecatcher#2]
Would it be possible? I want to automate a few things and would like sms to be converted to http requests so that my server can handle them

**Comment by headersalreadysent** [comment]
Hi,

Codecatcher does not use any internet connection for guaranteed privacy. Http post is not possible at this moment.
But I am planing a plugin system over intent.

**Comment by Flinner** [comment]
I found this https://github.com/bogkonstantin/android_income_sms_gateway_webhook

thanks !!
